### ISSUE TITLE
Use CloseableHttpClient + org.apache.http.conn.HttpClientConnectionManager (httpclient 4.3 API)

### ISSUE THREAD

**Issue by ceefour** [helun/Ektorp#134]
This depends on #133.

I separate this issue because using 4.3 `CloseableHttpClient` will be a breaking change for some advanced users of ektorp, because the `ConnectionManager` API also changes.

For our case, we already use 4.3 anyway so would be great if ektorp uses the new ConnectionManager. As of now we have two ConnectionManagers in memory, the old 4.2 one for ektorp and the 4.3 one for the rest of the app, which is slightly inefficient but workable.

**Comment by rudiw** [comment]
Using HttpClient 4.3 has a nice side-effect of fixing issues with SSL `SubjectAltName` which wasn't supported correctly in 4.2, resulting in errors like:

```
javax.net.ssl.SSLException: hostname in certificate didn't match: <pic.tuneeca.com> != <ssl2000.cloudflare.com> OR <ssl2000.cloudflare.com> OR <cloudflare.com> OR <*.cloudflare.com>
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:238)
	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:159)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:140)
	at org.apache.http.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:561)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:536)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at id.co.bippo.product.util.HttpClientSsl2Test.subjectAltName(HttpClientSsl2Test.java:34)
```

**Comment by ceefour** [comment]
Indeed @rudiw is correct, see https://issues.apache.org/jira/browse/HTTPCLIENT-1119
