### ISSUE TITLE
NPE with httpclient 4.4

### ISSUE THREAD

**Issue by huxi** [helun/Ektorp#222]
```
Caused by: java.lang.NullPointerException
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:489)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:126)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:215)
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1191)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:753)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
	at org.ektorp.impl.StdCouchDbConnector$5.success(StdCouchDbConnector.java:250)
	at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:122)
	at org.ektorp.http.RestTemplate.get(RestTemplate.java:22)
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:246)
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:237)
	at org.ektorp.support.StdDesignDocumentFactory.getFromDatabase(StdDesignDocumentFactory.java:57)
	at org.ektorp.support.CouchDbRepositorySupport.initDesignDocInternal(CouchDbRepositorySupport.java:280)
	at org.ektorp.support.CouchDbRepositorySupport.initStandardDesignDocument(CouchDbRepositorySupport.java:274)
```

This exception is thrown after upgrading httpclient from 4.3.6 to 4.4 (using Java8u31).

I reverted for now but wanted to inform you about this problem.

**Comment by YannRobert** [comment]
I upgraded my apps from 4.3.6 to 4.4 and did not found any issue.
Maybe you should upgrade ektorp to latest version (1.4.3) ?

**Comment by huxi** [comment]
But [1.4.2](https://repo1.maven.org/maven2/org/ektorp/org.ektorp/) is the latest released version...

**Comment by YannRobert** [comment]
I suppose @helun did not release 1.4.3 after all?
https://github.com/helun/Ektorp/commit/720ca25c0d89592887946d368447714d70c533b3

I'm using unreleased version myself, along with non-default configuration.

Maybe you should build a snapshot with the latest revision from master in order to test if you still get the error.

**Comment by huxi** [comment]
Just built the current HEAD and run our tests with it. Similar error, just on a slightly different line:
```
java.lang.NullPointerException: null
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:489)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:126)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:215)
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1191)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:753)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
	at org.ektorp.impl.StdCouchDbConnector$5.success(StdCouchDbConnector.java:244)
	at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:126)
	at org.ektorp.http.RestTemplate.get(RestTemplate.java:22)
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:240)
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:231)
	at org.ektorp.support.CouchDbRepositorySupport.get(CouchDbRepositorySupport.java:133)
```

**Comment by YannRobert** [comment]
What is the server HTTP Status and Response content? Are you sure they are valid?
It seems the HttpEntity is returning a null InputStream on getContent().

Would you like to build https://github.com/YannRobert/Ektorp/commit/e26580fed7f0327946131c5c6787d97339190359 and quick test again? I did a lot of changes back at a time for a better support of httpclient 4 that I didn't reported upstream.

If it still does not work it would help that you provide a test.

**Comment by huxi** [comment]
I hacked some output into `StdHttpResponse.getContent()` and ran my tests with httpclient 4.3.6 and httpcore 4.3.3 (working) as well as httpclient 4.4 and httpcore 4.4 (broken).

The first difference in the output (ignoring object identifiers of `toString()`) looks like this:
### working
```
Entity: org.apache.http.impl.client.cache.CacheEntity@41d426b5
Entity.getContentEncoding(): null
Entity.getContentLength(): 105
Entity.getContentType(): Content-Type: text/plain; charset=utf-8
Entity.isChunked(): false
Entity.isRepeatable(): true
Entity.isStreaming(): false
Entity.getContent(): java.io.ByteArrayInputStream@8dbfffb
```

### broken
```
Entity: org.ektorp.http.StdHttpResponse$NullEntity@4612b856
Entity.getContentEncoding(): Content-Encoding: UTF-8
Entity.getContentLength(): 0
Entity.getContentType(): Content-Type: null
Entity.isChunked(): false
Entity.isRepeatable(): true
Entity.isStreaming(): false
Entity.getContent(): null
```

I'll give your code a try in a few minutes.

**Comment by huxi** [comment]
I can't build your `integration` branch.

```
[INFO] Fork Value is true
     [java] The following errors occurred during analysis:
     [java] Feb 05, 2015 7:49:04 PM edu.umd.cs.findbugs.TextUIBugReporter reportAnalysisError
     [java] SEVERE: Unable to get XClass for java/util/function/Consumer
     [java] java.lang.ArrayIndexOutOfBoundsException: 27695
     [java] 	at org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java] 	at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:565)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java] 	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:266)
     [java] 	at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java] 	at edu.umd.cs.findbugs.ba.AnalysisCacheToAnalysisContextAdapter.setAppClassList(AnalysisCacheToAnalysisContextAdapter.java:391)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:981)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:224)
     [java] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:391)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1298)
```

Probably caused by Java 8?

**Comment by huxi** [comment]
Managed to build your `integration` branch with Java 7. Doesn't work either but gives a different exception:
```
org.ektorp.DbAccessException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.InputStreamReader@6c45ee6e; line: 1, column: 1]
	at org.ektorp.util.Exceptions.propagate(Exceptions.java:19)
	at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:132)
	at org.ektorp.http.RestTemplate.get(RestTemplate.java:22)
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:247)
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:237)
	at org.ektorp.support.CouchDbRepositorySupport.get(CouchDbRepositorySupport.java:133)
```

**Comment by huxi** [comment]
I forgot to mention that I'm running the tests against CouchDB 1.6.0 - if that makes a difference...

**Comment by huxi** [comment]
This is the way I create the `StdCouchDbInstance` in my tests:
```java
StdHttpClient.Builder builder = new StdHttpClient.Builder()
		.host("localhost")
		.port(5984);

Properties props =  new Properties();
File propFile = new File(System.getProperty("user.home"), "couchDbCredentials.properties");
InputStream is = null;
try {
	is = new FileInputStream(propFile);
	props.load(is);
}
catch(IOException ex) {
	props = null;
}
finally
{
	if(is != null)
	{
		try {
			is.close();
		} catch (IOException e) {
			// ignore
		}
	}
}

if(props!=null) {
	builder.username(props.getProperty("couch.user")).password(props.getProperty("couch.password"));
}

dbInstance = new StdCouchDbInstance(builder.build());
```

`dbInstance` is then used to create a `StdCouchDbConnector`
```java
StdCouchDbConnector db = new StdCouchDbConnector(dbName, couchDbInstance, new SomeObjectMapperFactory());
```
which is in turn used as a c'tor argument for a type-specific `CouchDbRepositorySupport` class. This class has several custom views
```java
@Views({
		@View(name = "all", file="/couch/foo/allView.json"),
		@View(name = "null_tags", file="/couch/foo/fooWithoutTags.json"),
		@View(name = "tag_counts", file="/couch/foo/fooTagCounts.json")
})
```
and calls `initStandardDesignDocument();` in the c'tor after calling `super(Foo.class, db)`.

That's all the info I can think of right now...

**Comment by YannRobert** [comment]
@huxi when using ApacheHC 4.x you need to change the way you instantiate the Apache HttpClient. 

I have a working Spring XML Context file that does that 
https://github.com/YannRobert/Ektorp/blob/a8b6d3c53f75cc6dd1d2644ed8ea88a427f4ff68/org.ektorp.spring/src/test/resources/ektorp-httpclient-config-4.xml

For the moment it depends on code that is not released in Ektorp.

The following branch https://github.com/YannRobert/Ektorp/tree/SupportingNewestVersionsOfApacheHttpComponent should contain all that is needed (but it contains more than what is needed)

**Comment by huxi** [comment]
But... it still works with 4.3.6.

I'll have to wait for a released ektorp version to use this in our production system so I just stay at 4.3.6 for now.

Configuration looks quite a bit more complex. Wouldn't it be possible to prevent some of it by using sensible defaults? Or is this already the case and your config example simple configures everything that is possible?

**Comment by pdeschen** [comment]
Getting the same issue with 4.5.2. It would be nice to see a release update. 

@helun what are your plan regarding a new release?

**Comment by cnsgithub** [comment]
The issue still remains with httpclient-4.5.3. Please fix it or at least provide a workaround. Thanks.

**Comment by amischler** [comment]
I'm getting the same issue with a fresh build of Ektorp 1.4.5-SNAPSHOT and httpclient-4.5.1. Did anyone find a workaround for this ? Are there any commits from Yann Robert's [SupportingNewestVersionsOfApacheHttpComponent branch](https://github.com/YannRobert/Ektorp/tree/SupportingNewestVersionsOfApacheHttpComponent) that might help and that have not been merged upstream yet ?

**Comment by amischler** [comment]
I merged the SupportingNewestVersionsOfApacheHttpComponent branch of Yann Robert's fork into helun/Ektorp master branch (1.4.5-SNAPSHOT) and it seems to be working fine with httpclient-4.5.1 (see https://github.com/amischler/Ektorp).

Should I create a PR ?

_Note : the configuration of the http client is a bit more complex now :_

```
RequestConfig requestConfig = RequestConfig.custom().build();
ConfigurableHttpRequestRetryHandler retryHandler = new ConfigurableHttpRequestRetryHandler();
retryHandler.setIncludeExceptionInLogs(true);
CredentialsProvider credentialsProvider = new CredentialsProviderConfigurer.DefaultCredentialsProvider();
CredentialsProviderConfigurer credentialsProviderConfigurer = new CredentialsProviderConfigurer();
credentialsProviderConfigurer.setHost("localhost");
credentialsProviderConfigurer.setPort(5984);
credentialsProviderConfigurer.setUsername(couchDbConfiguration.getUserName());
credentialsProviderConfigurer.setPassword(couchDbConfiguration.getPassword());
credentialsProviderConfigurer.setCredentialsProvider(credentialsProvider);
credentialsProviderConfigurer.configure();
PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
CouchDbDefaultRoutePlanner routePlanner = new CouchDbDefaultRoutePlanner();
routePlanner.setServerHostName("localhost");
routePlanner.setServerHostPort(5984);
HttpClientBuilder httpClientBuilder = HttpClientBuilder.create()
  .setKeepAliveStrategy(new ConfigurableConnectionKeepAliveStrategy())
  .setRetryHandler(retryHandler)
  .setConnectionReuseStrategy(new CustomConnectionReuseStrategy())
  .setRoutePlanner(routePlanner)
  .setDefaultRequestConfig(requestConfig)
  .setDefaultCredentialsProvider(credentialsProvider)
  .setConnectionManager(connectionManager);
AuthenticatedCloseableHttpClientRequestExecutor requestExecutor = new AuthenticatedCloseableHttpClientRequestExecutor();
requestExecutor.setServerHostName("localhost");
requestExecutor.setServerHostPort(5984);
requestExecutor.setBackendBuilder(httpClientBuilder);
requestExecutor.setClientBuilder(httpClientBuilder);
requestExecutor.init();
httpClient = new StdHttpClient(requestExecutor);
```

**Comment by YannRobert** [comment]
Hi @amischler 

Great to see the [SupportingNewestVersionsOfApacheHttpComponent branch](https://github.com/YannRobert/Ektorp/tree/SupportingNewestVersionsOfApacheHttpComponent) is working for you.

I can confirm that this code is currently in use on one of my project for several years now.

I worked on this a long time ago, so I am not sure what it contains exactly. 
I would have to review it. It contains many commits so it's difficult.

One concern would be to check it does not break things for users of older versions of Apache HC.

Any feedback would be appreciated and would help in getting it merged.

**Comment by robertgartman** [comment]
Just got hit by the this issue - triggered by the Amazon S3 API which won't play with the 4.3.6 HTTP Client version.

@YannRobert and @amischler 
Given you efforts - would it be an option for you to release a 2.0.0 version with a breaking change notification? The time required to verify (and maintain) backwards compatibility with the 2014 release of HC might be of better use in other areas.

**Comment by YannRobert** [comment]
Hi @robertgartman. Thank you for the comment. 
Given that this issue hits more and more people, we will sure need to address this.

I'll try to work on that by next week.

**Comment by robertgartman** [comment]
Trying with the version by @amischler landed in the _No content to map..._.

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.InputStreamReader@af29cfa; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2887) ~[jackson-databind-2.8.8.jar:2.8.8]
	at org.ektorp.http.ClassInstanceResponseHandler.success(ClassInstanceResponseHandler.java:46) ~[org.ektorp-1.4.5-SNAPSHOT.jar:?]
	at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:130) ~[org.ektorp-1.4.5-SNAPSHOT.jar:?]
	at org.ektorp.http.RestTemplate.get(RestTemplate.java:22) ~[org.ektorp-1.4.5-SNAPSHOT.jar:?]
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:247) ~[org.ektorp-1.4.5-SNAPSHOT.jar:?]
	at org.ektorp.impl.StdCouchDbConnector.get(StdCouchDbConnector.java:237) ~[org.ektorp-1.4.5-SNAPSHOT.jar:?]
```

**Comment by amischler** [comment]
I did not experience this issue with the merged version. Note that we are not making an intensive use of Ektorp, we are just evaluating the Ektorp + CouchDB solution for the moment.

Maybe something wen't wrong when I solved some conflicts during merging ? In this case a unit test for the case you are experiencing might be missing ;)

**Comment by huxi** [comment]
Any news on this?

**Comment by maratynsky** [comment]
Setting `StdHttpClient.caching` to `false` helped me. Version 1.4.3

**Comment by felixhall** [comment]
I ran into this when I upgraded Spring Boot 1.5 -> 2.0.
It caused an upgrade of Jackson, which in turn forced me to upgrade to Ektorp 1.5, after which my "all"-views for designs stopped working with similar stack traces as @huxi above.

Solved it by disabling StdHttpClient.caching using Java configuration of Spring Boot, something like:

```
@Bean
public CouchDbConnector getCouchDb() throws Exception {
        StdHttpClient.Builder httpClientBuilder = new StdHttpClient.Builder();
        httpClientBuilder.url(getDatabaseUrl()).caching(false);  // <-- Here
        // (..)
        CouchDbConnector dbConnector = new StdCouchDbConnector(getDatabaseName(),
                new StdCouchDbInstance(httpClientBuilder.build()), omf);
        dbConnector.createDatabaseIfNotExists();
        return dbConnector;
}
```
Thanks @maratynsky !

**Comment by gesellix** [comment]
As of HttpClient-Cache 4.4+ `HEAD` requests will be cached. This seems to break in cases where the `HEAD` request comes first before any subsequent `GET` requests on the same target. In other words: if you can use `httpclient-cache:4.3.x` in your setup, you should be able to work around that issue. Details/demo see https://github.com/gesellix/httpclient-cache-demo. I've already started a discussion about that issue at the httpclient-users mailing list: https://lists.apache.org/thread.html/8cb4252482565e0f6d59b097320cfbf572c212508b63e9fc59a2e1b4@%3Chttpclient-users.hc.apache.org%3E - feel free to join.
