### ISSUE TITLE
Page give “no message for java.lang.NullPointerException” if only one doc in lastpage

### ISSUE THREAD

**Issue by yyloveyhyy** [helun/Ektorp#252]
Exception in thread "main" org.ektorp.DbAccessException: com.fasterxml.jackson.databind.JsonMappingException: [no message for java.lang.NullPointerException]
	at org.ektorp.util.Exceptions.propagate(Exceptions.java:19)
	at org.ektorp.PageRequest.asLink(PageRequest.java:117)
	at org.ektorp.Page.getPreviousLink(Page.java:91)
	at com.dinfo.china.mobile.util.QueryUtil.main(QueryUtil.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: [no message for java.lang.NullPointerException]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2718)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:2233)
	at org.ektorp.PageRequest.asLink(PageRequest.java:114)
	... 7 more

**Comment by yyloveyhyy** [comment]
public static void main(String[] args) {
        String nextLink = null;
        String previLink = null;
        int page = 0;
        do {
            ViewQuery query = new ViewQuery().designDocId("_design/" + "docType").viewName("getDocByDocType").reduce(false);
            PageRequest pageRequest = nextLink != null ? PageRequest.fromLink(nextLink) : PageRequest.firstPage(10);
            //query.key("tc");
            Page result = BusinessUtil.connector.queryForPage(query,pageRequest,Object.class);
            System.out.println("totalcount :"+result.getTotalSize());
            System.out.println("currentPage:"+(page+1));
            page++;
            System.out.println("hasPre?"+result.isHasPrevious());
            if(result.isHasNext()){
                nextLink = result.getNextLink();
                System.out.println("nextLink:   "+nextLink);
            }else{
                nextLink =  null;
            }

            if(result.isHasPrevious()){
                previLink = result.getPreviousLink();
                System.out.println ("previousLink:   "+previLink);
            }
        }
        while (nextLink!=null);
    }


this is my code
