### ISSUE TITLE
ektorp 1.4.4 is incompatible with Jackson 2.9.0

### ISSUE THREAD

**Issue by huxi** [helun/Ektorp#269]
Stacktrace:
```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.withSerializationInclusion(Lcom/fasterxml/jackson/annotation/JsonInclude$Include;)Lcom/fasterxml/jackson/databind/SerializationConfig;
	at org.ektorp.impl.StdObjectMapperFactory.applyDefaultConfiguration(StdObjectMapperFactory.java:50)
	at org.ektorp.impl.StdObjectMapperFactory.createObjectMapper(StdObjectMapperFactory.java:26)
	at org.ektorp.impl.StdCouchDbInstance.<init>(StdCouchDbInstance.java:40)
	at org.ektorp.impl.StdCouchDbInstance.<init>(StdCouchDbInstance.java:32)
```

This was originally raised in #268. See [this comment](https://github.com/helun/Ektorp/issues/268#issuecomment-319396468) for a hint about how to address this.

**Comment by YannRobert** [comment]
Please see PR #270 for a change that would allow to inject an overridden instance of class org.ektorp.impl.StdObjectMapperFactory
