### ISSUE TITLE
Doesn't run with jackson 2.9

### ISSUE THREAD

**Issue by mihxil** [helun/Ektorp#277]
We have jackson 2.9 in our project.

Ektorp fails like so:

```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.withSerializationInclusion(Lcom/fasterxml/jackson/annotation/JsonInclude$Include;)Lcom/fasterxml/jackson/databind/SerializationConfig;
	at org.ektorp.impl.StdObjectMapperFactory.applyDefaultConfiguration(StdObjectMapperFactory.java:50)
	at org.ektorp.impl.StdObjectMapperFactory.createObjectMapper(StdObjectMapperFactory.java:26)
	at org.ektorp.impl.StdCouchDbInstance.<init>(StdCouchDbInstance.java:40)
	at org.ektorp.impl.StdCouchDbInstance.<init>(StdCouchDbInstance.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

**Comment by YannRobert** [comment]
Hi @mihxil 
Yes, it is a known issue (see #269)
A fix has been merged into master.
But I did not released yet. I'll (try to) find some time this week to release.

**Comment by mihxil** [comment]
Ok, that would be nice. Thanks!

**Comment by YannRobert** [comment]
Version 1.5.0 is released and available on maven central repository.
http://search.maven.org/#artifactdetails%7Corg.ektorp%7Corg.ektorp%7C1.5.0%7C
