### ISSUE TITLE
Unable to  create documents and attaching files simultaneously

### ISSUE THREAD

**Issue by swedhaselva** [helun/Ektorp#289]
this is my service implementation:

```
public String createAttachment(String docId) throws FileNotFoundException{
	try {
		CouchDbInstance dbInstance = getconnection();

		// creating database

		CouchDbConnector connector = new StdCouchDbConnector("demouser", dbInstance);
		CouchDbImpl impl = new CouchDbImpl(connector);
		connector.createDatabaseIfNotExists();

		String database = connector.getDatabaseName();
		System.out.println(database);
		
		InputStream inputstream = new FileInputStream("C:\\Users\\SwedhaS\\Desktop\\couchdb reference.txt");
		String contentType = "application/text";

		AttachmentInputStream a = new AttachmentInputStream("123456",
		                                                     inputstream,
		                                                     contentType);

		connector.createAttachment(docId, a);
	


	} catch (MalformedURLException e) {

		e.printStackTrace();
	}

	return null;
}
```
	this is my controller:

```
@PostMapping("/save/{id}")
	public String createDocumentAndfiles(@RequestBody User user,@PathVariable String id) throws FileNotFoundException {
	String users=userRepo.createAttachment(id);
	return users;
	}

```

**Comment by jocafi** [comment]
I am getting similar error. 

The unit test below fails on the line:
**animalCouchDbService.createAttachment(animal.getId(), ais);**

```
  @Test
  @DisplayName("Save and read an image as attachment")
  void saveAndReadAttachment() throws IOException {
    Animal animal = AnimalFactory.createAnimal("Giraffe_with_Attachment", AnimalType.MAMMAL);
    Animal animalRet = animalCouchDbService.create(animal);
    assertThat(animal.getId(), equalTo(animalRet.getId()));
    assertThat(animal.getAttachments(), nullValue());

    InputStream data = this.getClass().getClassLoader().getResourceAsStream ("tank_icon.png");
    AttachmentInputStream ais = new AttachmentInputStream("att_giraffe_id_01", data,   "image/png");
    animalCouchDbService.createAttachment(animal.getId(), ais);

    Animal readAnimal = animalCouchDbService.read(Animal.class, animalRet.getId());
    assertThat(readAnimal.getId(), equalTo(animalRet.getId()));

    Attachment attachment = readAnimal.getAttachments().get("att_giraffe_id");
    assertThat(attachment.getContentType(), is("image/png"));
    assertThat(attachment.getDataBase64(), nullValue());

    AttachmentInputStream readAttachment = animalCouchDbService.readAttachment(readAnimal);
    BufferedImage readImage = ImageIO.read(readAttachment);
    assertThat(readImage, notNullValue());
  }

```

Then I get the error:

Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:867)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.apache.http.impl.client.cache.CachingHttpClient.callBackend(CachingHttpClient.java:747)
	at org.apache.http.impl.client.cache.CachingHttpClient.execute(CachingHttpClient.java:446)
	at org.apache.http.impl.client.cache.CachingHttpClient.execute(CachingHttpClient.java:339)
	at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:177)
	... 62 more
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity.  The cause lists the reason the original request failed.
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:656)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	... 68 more
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:159)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:179)
	at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:124)
	at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:181)
	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:132)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
	at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:265)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:203)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:682)
	... 70 more

**Comment by jocafi** [comment]
It worked now. I read the documentation and I did not understand the use of the method below in the section **Create Document and Attachment in one operation**

`db.createAttachment("new_document_id", a);`

I do not have any "new_document_id". I have the document Id from the document that was created one step before and it is new (in my opinion). Why this section is called **Create Document and Attachment in one operation** ? I could not create document and attachment in one operation.

Well, at the end I used the command below and it worked. It is from the section **Add an Attachment to an Existing Document**:

`db.createAttachment(t.getId(), t.getRevision(), attachment);`

I hope it can help you and another people.

Cheers !!!
